#!/bin/bash

# COMMANDS #

VERSION=1.0.0

setup() {
  chmod +x setup.sh
  ./setup.sh
}

start() {
  echo "Starting web server..."
  node server.js
}

version() {
  echo "Rush V$VERSION"
}

help() {
  echo "Usage: rush <command>"
  echo "Commands:"
  echo "  start  Start the web server"
  echo "  help  Display this help message"
  echo "  setup  Setup Rush"
  echo "  version  Display the version of Rush"
}

if [ $# -eq 0 ]; then
  echo "Error: No command provided. Please use 'rush help' for a list of commands"
  exit 1
fi

case "$1" in
  start)
    start
    ;;
  help)
    help
    ;;
  setup)
    setup
    ;;
  version)
    version
    ;;
  *)
    echo "Error: Invalid command '$1'. Use 'rush help' for a list of commands."
    exit 1
    ;;
esac
